### ISSUE TITLE
Write a scrapper from BrainyQuote

### ISSUE THREAD

**Issue by akshatkarani** [oss2019/pyquotes#1]
Given the name of a person and a category, scrap all the quotes from [BrainyQuote](https://www.brainyquote.com/).

**Comment by Rits1272** [comment]
I will take up this issue!

**Comment by bymayanksingh** [comment]
I am Interested in taking this one +1 @akshatkarani

**Comment by akshatkarani** [comment]
@Rits1272 @code-monk08 Please work together and have a working code(not clean, but working) within a week.
Also, I will not assign anyone else to this. So if someone is interested, try scrapping from a different website.

**Comment by bymayanksingh** [comment]
@akshatkarani sure, I can try scrapping other websites for now, Thanks.

Edit:
I am working with [powerquotations.com](https://www.powerquotations.com/)

**Comment by mukul-mehta** [comment]
Hi Akshat. Me and @rakaar can try scraping from Wikiquote.

**Comment by akshatkarani** [comment]
Closed by https://github.com/oss2019/pyquotes/pull/6
