### ISSUE TITLE
Let's do Hacktoberfest.

### ISSUE THREAD

**Issue by sunn-e** [oss2019/pyquotes#45]
Hey guys, this is sunn-e. Since Hacktoberfest has already started, we think it would be a good opportunity to take this project further.
For getting started, go to https://hacktoberfest.digitalocean.com/.

> What is hacktoberfest.

Hacktoberfest® is open to everyone in our global community. Whether you’re a developer, student learning to code, event host, or company of any size, you can help drive growth of open source and make positive contributions to an ever-growing community. All backgrounds and skill levels are encouraged to complete the challenge. 

> Eh,what about the sweet goodies?

Support open source and earn a limited edition T-shirt by Digital Ocean!
 
> Yo,what are rules?

To qualify for the official limited edition Hacktoberfest shirt, you must register and make four pull requests (PRs) between October 1-31 (in any time zone). PRs can be made to any public repo on GitHub, not only the ones with issues labeled Hacktoberfest. If a maintainer reports your pull request as spam or behavior not in line with the project’s code of conduct, you will be ineligible to participate. This year, the first 50,000 participants who successfully complete the challenge will earn a T-shirt. 
https://hacktoberfest.digitalocean.com/faq#rules its a long list.

Get going good guys.

**Comment by sonusourav** [comment]
Yeah! Even I have labeled issues of my repo with Hacktoberfest. And some people are showing interest.

**Comment by akshatkarani** [comment]
Nice thought, but wrong repository.
